#! /bin/sh

case "$1" in
	start)
		modprobe brcmfmac.ko
		sleep 1
		ifconfig wlan0 192.168.3.100
		hostapd -B /etc/hostapd.conf
		echo 1 > /proc/sys/net/ipv4/ip_forward
		ifconfig eth0 up
		iptables -F
		iptables -t nat -A POSTROUTING -s 192.168.3.0/24 -o eth0 -j MASQUERADE
		sleep 1
		mentohust &
		;;
	stop)
		mentohust -k
		rmmod brcmfmac.ko
		rmmod brcmutil.ko
		;;
	*)
		exit 1
		;;
esac
